# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagseguro', '0002_auto_20150506_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreApprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(choices=[('auto', 'Autom\xe1tica'), ('manual', 'Manual')], db_index=True, help_text='Indica se a assinatura ser\xe1 gerenciada pelo PagSeguro (autom\xe1tica) ou pelo Vendedor (manual)', max_length=20, verbose_name='Cobran\xe7a')),
                ('name', models.CharField(db_index=True, help_text='Nome/Identificador da assinatura', max_length=100, unique=True, verbose_name='Nome')),
                ('details', models.TextField(blank=True, help_text='Detalhes/Descri\xe7\xe3o da assinatura', max_length=255, verbose_name='Detalhes')),
                ('amount_per_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Valor exato de cada cobran\xe7a', max_digits=9, null=True, verbose_name='Valor da cobran\xe7a')),
                ('max_amount_per_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Valor m\xe1ximo de cada cobran\xe7a', max_digits=9, null=True, verbose_name='Valor m\xe1ximo de cada cobran\xe7a')),
                ('period', models.CharField(choices=[('WEEKLY', 'semanal'), ('MONTHLY', 'mensal'), ('BIMONTHLY', '2 vezes ao m\xeas'), ('TRIMONTHLY', '3 vezes por m\xeas'), ('SEMIANNUALLY', 'A cada 6 meses'), ('YEARLY', 'Anualmente')], db_index=True, help_text='Periodicidade da cobran\xe7a', max_length=20, verbose_name='Periodicidade')),
                ('final_date', models.DateTimeField(db_index=True, help_text='Fim da vig\xeancia da assinatura', verbose_name='Data Final')),
                ('max_total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor m\xe1ximo de cada cobran\xe7a', max_digits=9, null=True, verbose_name='Valor m\xe1ximo de cada cobran\xe7a')),
                ('reference', models.CharField(blank=True, db_index=True, help_text='A refer\xeancia passada na transa\xe7\xe3o.', max_length=200, null=True, verbose_name='Refer\xeancia')),
                ('redirect_code', models.CharField(blank=True, help_text='C\xf3digo gerado para redirecionamento.', max_length=100, null=True, verbose_name='c\xf3digo')),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinaturas',
            },
        ),
        migrations.CreateModel(
            name='PreApprovalsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='C\xf3digo gerado para redirecionamento.', max_length=100, verbose_name='c\xf3digo')),
                ('date', models.DateTimeField(help_text='Data em que a assinatura foi realizada.', verbose_name='Data')),
                ('success', models.BooleanField(db_index=True, default=False, help_text='A assinatura foi feito com sucesso?', verbose_name='Sucesso')),
                ('message', models.TextField(blank=True, help_text='Mensagem apresentada no caso de erro na assinatura.', verbose_name='Mensagem de erro')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Assinatura Request',
                'verbose_name_plural': 'Assinaturas Request',
            },
        ),
    ]
