# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagseguro', '0003_preapprovals_preapprovalsrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('1', 'Pagamento'), ('11', 'Recorr\xeancia')], db_index=True, default='1', help_text='Representa o tipo da transa\xe7\xe3o recebida.', max_length=2, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='preapprovals',
            name='period',
            field=models.CharField(choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('BIMONTHLY', '2 vezes ao m\xeas'), ('TRIMONTHLY', '3 vezes por m\xeas'), ('SEMIANNUALLY', 'A cada 6 meses'), ('YEARLY', 'Anualmente')], db_index=True, help_text='Periodicidade da cobran\xe7a', max_length=20, verbose_name='Periodicidade'),
        ),
    ]
